#!/usr/bin/python
#encoding: utf-8

#############################################################################
## 							   Proyecto traductores e Interpretadores  							   ##
##															    SETLAN												  		   ##
#############################################################################
#																																						#
#														---(Primera Entrega)---									 				#
#Integrantes:																																#
#		Nelson Saturno 09-10797																		 							#
#		Neylin Belisario 09-10093																	 							#
#												 																										#
#############################################################################


import sys
import lexer
import parser

def main():

	if (len(sys.argv) > 1):
		if len(sys.argv) == 3:
			if sys.argv[1] == "-t":
				te = lexer.lexicografico(sys.argv[2],"imprime")
				if te:
					te[0].lexer.lineno = 0
				
		parser.AnalizadorParser(sys.argv[2])
	else:
		print "Verifique que la sintaxis introducida es correcta."
		print ".\\setlan.py <nombre del archivo>\n"


if __name__ == "__main__":
	main()

